### ISSUE TITLE
Tag a new version?

### ISSUE THREAD

**Issue by Potherca** [cloudogu/plantuml-cloudogu-sprites#7]
Hi! 👋 

As there are [27 commits to master](https://github.com/cloudogu/plantuml-cloudogu-sprites/compare/v1.0.2...master) since the v1.0.2 release, would it be possible to tag a new release?

These changes have already been merged upstream in https://github.com/plantuml/plantuml-stdlib/pull/109 but having a new tag would allow updating the [`INFO`](https://github.com/plantuml/plantuml-stdlib/blob/master/cloudogu/INFO) file so we can more easily track future changes.

**Comment by alexander-dammeier** [comment]
Hi, 
thank you for your issue! I just released v1.1.0.

Please notice that we [want to change the license](https://platform.cloudogu.com/en/blog/lizenzaenderungt-agpl3/) of our repositories to AGPL 3.0. 
Since there is no real code in this repository and we have no interest in restricting reuse for open source projects, I can talk to our lawyer about making an exception for this repository and only using our usual MIT licence here.

**Comment by Potherca** [comment]
Awesome, thanks!
